const countryCodes = [
  { id: 1, strArea: 'American', isoCode: 'us' },
  { id: 2, strArea: 'British', isoCode: 'gb' },
  { id: 3, strArea: 'Canadian', isoCode: 'ca' },
  { id: 4, strArea: 'Chinese', isoCode: 'cn' },
  { id: 5, strArea: 'Croatian', isoCode: 'hr' },
  { id: 6, strArea: 'Dutch', isoCode: 'nl' },
  { id: 7, strArea: 'Egyptian', isoCode: 'eg' },
  { id: 8, strArea: 'Filipino', isoCode: 'ph' },
  { id: 9, strArea: 'French', isoCode: 'fr' },
  { id: 10, strArea: 'Greek', isoCode: 'gr' },
  { id: 11, strArea: 'Indian', isoCode: 'in' },
  { id: 12, strArea: 'Irish', isoCode: 'ie' },
  { id: 13, strArea: 'Italian', isoCode: 'it' },
  { id: 14, strArea: 'Jamaican', isoCode: 'jm' },
  { id: 15, strArea: 'Japanese', isoCode: 'jp' },
  { id: 16, strArea: 'Kenyan', isoCode: 'ke' },
  { id: 17, strArea: 'Malaysian', isoCode: 'my' },
  { id: 18, strArea: 'Mexican', isoCode: 'mx' },
  { id: 19, strArea: 'Moroccan', isoCode: 'ma' },
  { id: 20, strArea: 'Polish', isoCode: 'pl' },
  { id: 21, strArea: 'Portuguese', isoCode: 'pt' },
  { id: 22, strArea: 'Russian', isoCode: 'ru' },
  { id: 23, strArea: 'Spanish', isoCode: 'es' },
  { id: 24, strArea: 'Thai', isoCode: 'th' },
  { id: 25, strArea: 'Tunisian', isoCode: 'tn' },
  { id: 26, strArea: 'Turkish', isoCode: 'tr' },
  { id: 27, strArea: 'Ukrainian', isoCode: 'ua' },
  { id: 28, strArea: 'Vietnamese', isoCode: 'vn' },
  { id: 29, strArea: 'Unknown', isoCode: 'unknown' },
];

export default countryCodes;
